// Auto-generated list of canonical spell names for migration cleanup
export const CANONICAL_SPELL_NAMES: ReadonlySet<string> = new Set([
  "500 Toads",
  "Aberrant Form",
  "Abyssal Plague",
  "Acid Arrow",
  "Acid Grip",
  "Acid Splash",
  "Acid Storm",
  "Acidic Burst",
  "Admonishing Ray",
  "Advanced Scurvy",
  "Aerial Form",
  "Agitate",
  "Agonizing Despair",
  "Air Bubble",
  "Air Walk",
  "Airburst",
  "Airlift",
  "Alarm",
  "Albatross Curse",
  "All is One, One is All",
  "Allfood",
  "Alter Reality",
  "Anathematic Reprisal",
  "Ancestral Winds",
  "Ancient Dust",
  "Angel Form",
  "Animal Allies",
  "Animal Form",
  "Animal Messenger",
  "Animal Vision",
  "Animate Rope",
  "Animated Assault",
  "Animus Mine",
  "Annunciation of the Outer Gate",
  "Anointed Ground",
  "Ant Haul",
  "Anticipate Peril",
  "Antimagic Field",
  "Antlion Trap",
  "Approximate",
  "Aqueous Blast",
  "Aqueous Orb",
  "Arctic Rift",
  "Armor of Thorn and Claw",
  "Aromatic Lure",
  "Arrow Salvo",
  "Ash Cloud",
  "Astral Labyrinth",
  "Attacked from Within",
  "Augury",
  "Aura of the Unremarkable",
  "Avatar",
  "Avenging Wildwood",
  "Awaken Entropy",
  "Bandit's Doom",
  "Bane",
  "Banishing Touch",
  "Banishment",
  "Bee-Man's Summons",
  "Befitting Attire",
  "Befuddle",
  "Beheading Buzz Saw",
  "Behold the Weave",
  "Belittling Boast",
  "Benediction",
  "Beseech Arcanotheign",
  "Beseech the Sphinx",
  "Bestial Curse",
  "Bilocation",
  "Bind Undead",
  "Binding Muzzle",
  "Biting Words",
  "Black Tentacles",
  "Blackfinger's Blades",
  "Blade Barrier",
  "Blanket of Stars",
  "Blast of the Bellows",
  "Blastback",
  "Blazing Armory",
  "Blazing Blade",
  "Blazing Bolt",
  "Blazing Dive",
  "Blazing Fissure",
  "Bless",
  "Blessed Boundary",
  "Blessing of Defiance",
  "Blightburn Blast",
  "Blind Eye",
  "Blinding Bottle",
  "Blinding Foam",
  "Blinding Fury",
  "Blindness",
  "Blink Charge",
  "Blister",
  "Blister Bomb",
  "Blistering Invective",
  "Blood Duplicate",
  "Blood Feast",
  "Blood Vendetta",
  "Blood-Feasting Breath",
  "Bloodspray Curse",
  "Blur",
  "Boil Blood",
  "Bone Flense",
  "Bone Spray",
  "Boneshaker",
  "Bonewall Bulwark",
  "Boomerang Shot",
  "Boots on the Ground",
  "Bottomless Stomach",
  "Bound in Death",
  "Bounty of the Sky",
  "Bracing Tendrils",
  "Bralani Referendum",
  "Bramble Bush",
  "Brand the Impenitent",
  "Breadcrumbs",
  "Breath of Drought",
  "Breath of Life",
  "Breathe Fire",
  "Bridge of Vines",
  "Brine Dragon Bile",
  "Briny Bolt",
  "Buffeting Winds",
  "Bullhorn",
  "Buoyant Bubbles",
  "Burglar's Blind",
  "Burning Blossoms",
  "Burrow Ward",
  "Bursting Bloom",
  "Buzzing Servants",
  "Call Fluxwraith",
  "Call The Blood",
  "Calm",
  "Camel Spit",
  "Canticle of Everlasting Grief",
  "Carrion Mire",
  "Carryall",
  "Cast into Time",
  "Caster's Imposition",
  "Cataclysm",
  "Catch Your Name",
  "Caustic Blast",
  "Cauterize Wounds",
  "Cave Fangs",
  "Celestial Accord",
  "Chain Lightning",
  "Chameleon Coat",
  "Channel Arrogance",
  "Charitable Urge",
  "Charm",
  "Chilling Darkness",
  "Chilling Spray",
  "Chroma Leach",
  "Chromatic Armor",
  "Chromatic Image",
  "Chromatic Ray",
  "Chromatic Wall",
  "Chrysopoetic Curse",
  "Cinder Swarm",
  "Circle of Protection",
  "Clad In Metal",
  "Claim Curse",
  "Clairaudience",
  "Clairvoyance",
  "Claws of the Otter",
  "Clawsong",
  "Cleanse Affliction",
  "Cleanse Air",
  "Cleanse Cuisine",
  "Clear Mind",
  "Cloak of Colors",
  "Cloak of Light",
  "Clockwork Devotion",
  "Clone Companion",
  "Cloud Current",
  "Cloud Dragon's Cloak",
  "Clownish Curse",
  "Coiling Dance",
  "Collective Transposition",
  "Command",
  "Compel True Name",
  "Concordant Choir",
  "Conductive Weapon",
  "Cone of Cold",
  "Confetti Cloud",
  "Confusing Colors",
  "Confusing Cry",
  "Confusion",
  "Conjured Conveyance",
  "Conquering Soldiers",
  "Consecrate Flesh",
  "Containment",
  "Contingency",
  "Control Sand",
  "Control Water",
  "Coral Eruption",
  "Coral Scourge",
  "Cordyceps Command",
  "Corrosive Body",
  "Corrosive Muck",
  "Cosmic Form",
  "Countless Eyes",
  "Cozy Cabin",
  "Crashing Wave",
  "Create Food",
  "Create Water",
  "Creation",
  "Crimson Breath",
  "Crisis of Faith",
  "Croak Voice",
  "Crusade",
  "Cup of Dust",
  "Curse of Lost Time",
  "Curse of Recoil",
  "Curse of the Spirit Orchestra",
  "Cursed Metamorphosis",
  "Cutting Insult",
  "Cycle of Retribution",
  "Cyclone Rondo",
  "Daemon Form",
  "Dancing Fountain",
  "Dancing Shield",
  "Darkness",
  "Darkvision",
  "Dawnflower's Light",
  "Day's Weight",
  "Daydreamer's Curse",
  "Daze",
  "Deafness",
  "Death Knell",
  "Death Ward",
  "Deathless March",
  "Deep Breath",
  "Deep Sight",
  "Defended by Spirits",
  "Dehydrate",
  "Deity's Strike",
  "Deluge",
  "Demon Form",
  "Desiccate",
  "Desperate Repair",
  "Detect Alignment",
  "Detect Creator",
  "Detect Magic",
  "Detect Metal",
  "Detect Poison",
  "Detect Scrying",
  "Detonate Magic",
  "Devil Form",
  "Devour Life",
  "Devouring Void",
  "Diadem of Divine Radiance",
  "Dimensional Excision",
  "Dinosaur Form",
  "Dinosaur Fort",
  "Dirge of Remembrance",
  "Disappearance",
  "Discern Lies",
  "Disguise Magic",
  "Disintegrate",
  "Disjunction",
  "Dismantle",
  "Dispel Magic",
  "Dispelling Globe",
  "Disruptive Transfer",
  "Distracting Chatter",
  "Dive and Breach",
  "Dividing Trench",
  "Divine Armageddon",
  "Divine Aura",
  "Divine Decree",
  "Divine Dragon's Watch",
  "Divine Immolation",
  "Divine Inspiration",
  "Divine Lance",
  "Divine Vessel",
  "Divine Wrath",
  "Divinity Leech",
  "Dizzying Colors",
  "Dominate",
  "Domora's Defense",
  "Dragon Form",
  "Dragon Turret",
  "Draw Ire",
  "Draw Moisture",
  "Draw the Lightning",
  "Dream Council",
  "Dream Message",
  "Dreaming Potential",
  "Drop Dead",
  "Dull Ambition",
  "Duplicate Foe",
  "Déjà Vu",
  "Eagle's Cry",
  "Earth and Sky",
  "Earthbind",
  "Earthquake",
  "Eat Fire",
  "Echo Jump",
  "Echoing Weapon",
  "Eclipse Burst",
  "Ectoplasmic Expulsion",
  "Electric Arc",
  "Element Embodied",
  "Elemental Absorption",
  "Elemental Annihilation Wave",
  "Elemental Breath",
  "Elemental Confluence",
  "Elemental Counter",
  "Elemental Form",
  "Elemental Gift",
  "Elemental Sense",
  "Elemental Zone",
  "Elephant Form",
  "Elysian Whimsy",
  "Embed Message",
  "Empathic Link",
  "Empty Pack",
  "Endure",
  "Energy Aegis",
  "Enervation",
  "Enfeeble",
  "Engrave Memory",
  "Enhance Senses",
  "Enhance Victuals",
  "Enlarge",
  "Entangle Fate",
  "Entangling Flora",
  "Enthrall",
  "Entrancing Eyes",
  "Entwined Roots",
  "Envenom Companion",
  "Environmental Endurance",
  "Equal Footing",
  "Erase Trail",
  "Ethereal Jaunt",
  "Etheric Shards",
  "Everlight",
  "Exchange Image",
  "Excise Lexicon",
  "Execute",
  "Expeditious Excavation",
  "Exploding Earth",
  "Explosive Barrage",
  "Extract Poison",
  "Fabricated Truth",
  "Faerie Fire",
  "Fallen Soldier's Lament",
  "Falling Sky",
  "Falling Stars",
  "False Nature",
  "False Vision",
  "False Vitality",
  "Falsify Heat",
  "Familiar's Face",
  "Far Sight",
  "Far-Flung Fetch",
  "Fashionista",
  "Fate's Travels",
  "Fated Confrontation",
  "Fated Healing",
  "Fateful Condemnation",
  "Favorable Review",
  "Fear",
  "Fear the Sun",
  "Feast of Ashes",
  "Feet to Fins",
  "Feral Shades",
  "Ferrous Form",
  "Fey Form",
  "Field of Life",
  "Field of Razors",
  "Fiery Body",
  "Figment",
  "Filter Air",
  "Final Fate of the Locust Host",
  "Final Sacrifice",
  "Fire Seeds",
  "Fire Shield",
  "Fire's Pathway",
  "Fireball",
  "Fireproof",
  "Firework Blast",
  "Flame Dancer",
  "Flame Strike",
  "Flame Vortex",
  "Flame Wisp",
  "Flames of Ego",
  "Flammable Fumes",
  "Flashy Disappearance",
  "Fleet Step",
  "Flense",
  "Flicker",
  "Floating Flame",
  "Flourishing Flora",
  "Flowing Strike",
  "Fly",
  "Focusing Hum",
  "Fold Metal",
  "Foraging Friends",
  "Forbidding Ward",
  "Force Barrage",
  "Forced Mercy",
  "Forceful Hand",
  "Foresight",
  "Forest of Gates",
  "Forge",
  "Forgotten Lines",
  "Freeze Time",
  "Freezing Rain",
  "Friendfetch",
  "Frigid Flurry",
  "Frog Tongue",
  "Frost Pillar",
  "Frost's Touch",
  "Frostbite",
  "Frozen Fog",
  "Funeral Flames",
  "Fungal Hyphae",
  "Fungal Infestation",
  "Gale Blast",
  "Garden of the Green Man's Growth",
  "Gasping Marsh",
  "Gate",
  "Gecko Grip",
  "Gentle Breeze",
  "Gentle Landing",
  "Geyser",
  "Ghost Sound",
  "Ghostly Carrier",
  "Ghostly Tragedy",
  "Ghostly Weapon",
  "Ghoulish Cravings",
  "Girzanje's March",
  "Glamorize",
  "Glass Form",
  "Glass Sand",
  "Glass Shield",
  "Glimmer of Charm",
  "Glowing Trail",
  "Goblin Pox",
  "Gouging Claw",
  "Grasp of the Deep",
  "Grasping Earth",
  "Grave Impressions",
  "Gravitational Pull",
  "Gravity Well",
  "Gray Shadow",
  "Grease",
  "Grim Tendrils",
  "Grisly Growths",
  "Gritty Wheeze",
  "Guidance",
  "Guiding Star",
  "Gust of Wind",
  "Hag's Fruit",
  "Halcyon Infusion",
  "Hallucination",
  "Harm",
  "Haste",
  "Haunting Hymn",
  "Heal",
  "Healing Plaster",
  "Healing Well",
  "Heat Metal",
  "Heatvision",
  "Heaving Earth",
  "Heinous Future",
  "Helpful Reload",
  "Helpful Steps",
  "Helpful Wood Spirits",
  "Heroism",
  "Hidden Mind",
  "Hidebound",
  "Hippocampus Retreat",
  "Holy Cascade",
  "Holy Host",
  "Holy Light",
  "Honeyed Words",
  "Horde of Underlings",
  "Horizon Thunder Sphere",
  "Horrifying Blood Loss",
  "Howling Blizzard",
  "Humanoid Form",
  "Hungry Depths",
  "Hydraulic Push",
  "Hydraulic Torrent",
  "Hypercognition",
  "Hypnopompic Terrors",
  "Hypnotize",
  "Ibex's Harvest",
  "Ice Storm",
  "Ignite Fireworks",
  "Ignition",
  "Ill Omen",
  "Illuminate",
  "Illusory Creature",
  "Illusory Disguise",
  "Illusory Object",
  "Illusory Scene",
  "Illusory Shroud",
  "Imaginary Lockbox",
  "Imp Sting",
  "Impaling Spike",
  "Impart Empathy",
  "Impeccable Flow",
  "Impending Doom",
  "Implement of Destruction",
  "Implosion",
  "Imprint Message",
  "Incendiary Fog",
  "Indestructibility",
  "Indolent Haze",
  "Inevitable Disaster",
  "Inexhaustible Cynicism",
  "Infectious Comedy",
  "Infectious Ennui",
  "Infectious Enthusiasm",
  "Infectious Melody",
  "Infiltrator's Tunnel",
  "Infuse Vitality",
  "Inkshot",
  "Inner Radiance Torrent",
  "Insect Form",
  "Inside Ropes",
  "Instant Armor",
  "Instant Minefield",
  "Instant Parade",
  "Instant Pottery",
  "Internal Insurrection",
  "Interplanar Teleport",
  "Interposing Earth",
  "Invisibility",
  "Invisibility Curtain",
  "Invisible Item",
  "Invoke Spirits",
  "Invoke True Name",
  "Iron Gut",
  "It is Written",
  "Item Facade",
  "Jassim's Allegiance",
  "Join Pasts",
  "Jump",
  "Juvenile Companion",
  "Kgalaserke's Axes",
  "Kinetic Ram",
  "King's Castle",
  "Knock",
  "Know Location",
  "Know the Way",
  "Lashing Rope",
  "Lashunta's Life Bubble",
  "Laughing Fit",
  "Leaden Steps",
  "Leng Sting",
  "Levitate",
  "Liberating Command",
  "Life Connection",
  "Life Pact",
  "Life's Flowing River",
  "Life's Fresh Bloom",
  "Life-Draining Roots",
  "Lifewood Cage",
  "Light",
  "Lightning Bolt",
  "Lightning Storm",
  "Lignify",
  "Liminal Doorway",
  "Linnorm Sting",
  "Live Wire",
  "Locate",
  "Lock",
  "Lock Item",
  "Loose Time's Arrow",
  "Lose the Path",
  "Lotus Walk",
  "Love's Sacrifice",
  "Lucky Number",
  "Lure Dream",
  "Luring Wail",
  "Mad Monkeys",
  "Magic Mailbox",
  "Magic Passage",
  "Magic Stone",
  "Magical Fetters",
  "Magnetic Acceleration",
  "Magnetic Attraction",
  "Magnetic Dominion",
  "Magnetic Repulsion",
  "Malediction",
  "Manifestation",
  "Manifestation of Spirits",
  "Mantis's Grasp",
  "Mantle of Heaven's Slopes",
  "Mantle of the Frozen Heart",
  "Mantle of the Magma Heart",
  "Mantle of the Melting Heart",
  "Mantle of the Unwavering Heart",
  "Mariner's Curse",
  "Mark of Blood",
  "Martyr's Intervention",
  "Marvelous Mount",
  "Mask of Terror",
  "Massacre",
  "Maze of Locked Doors",
  "Mending",
  "Mental Map",
  "Mercurial Stride",
  "Message",
  "Message Rune",
  "Metamorphosis",
  "Migration",
  "Mimic Spell",
  "Mimic Undead",
  "Mind Games",
  "Mind Probe",
  "Mind Reading",
  "Mind of Menace",
  "Mindlink",
  "Miracle",
  "Mirage",
  "Mirecloak",
  "Mirror Image",
  "Mirror Malefactors",
  "Mirror's Misfortune",
  "Mislead",
  "Missed Cue",
  "Mist",
  "Misty Memory",
  "Moment of Renewal",
  "Momentary Recovery",
  "Monstrosity Form",
  "Moon Frenzy",
  "Moonburst",
  "Moonlight Ray",
  "Morass of Ages",
  "Moth's Supper",
  "Mountain Resilience",
  "Movanic Glimmer",
  "Mud Pit",
  "Murderous Vine",
  "Musical Accompaniment",
  "Musical Shift",
  "Mutilate",
  "Mystic Armor",
  "Nature Incarnate",
  "Nature's Enmity",
  "Nature's Pathway",
  "Nature's Reprisal",
  "Necromancer's Generosity",
  "Necrotic Radiation",
  "Necrotize",
  "Needle Darts",
  "Negate Aroma",
  "Nettleskin",
  "Never Mind",
  "Nightmare",
  "Noise Blast",
  "Nothing Up My Sleeve",
  "Noxious Metals",
  "Noxious Vapors",
  "Nudge the Odds",
  "Nullify",
  "Oaken Resilience",
  "Object Reading",
  "Ocular Overload",
  "One with Plants",
  "One with Stone",
  "One with the Land",
  "Oneiric Mire",
  "Ooze Form",
  "Orb of Twisting Fate",
  "Organsight",
  "Osseous Cage",
  "Outcast's Curse",
  "Overselling Flourish",
  "Overwhelming Memory",
  "Overwhelming Presence",
  "Pack Attack",
  "Pain of Ages",
  "Painful Vibrations",
  "Painted Scout",
  "Paralyze",
  "Paranoia",
  "Part the Mists to Paradise",
  "Pave Ground",
  "Peaceful Bubble",
  "Peaceful Rest",
  "Penumbral Disguise",
  "Penumbral Shroud",
  "Perceive the Threads of Fate",
  "Percussive Impact",
  "Pernicious Poltergeist",
  "Perseis's Precautions",
  "Persistent Servant",
  "Personal Ocean",
  "Personal Rain Cloud",
  "Pest Form",
  "Pest Swarm",
  "Pet Cache",
  "Petal Storm",
  "Petrify",
  "Phantasmagoria",
  "Phantasmal Calamity",
  "Phantasmal Killer",
  "Phantasmal Minion",
  "Phantasmal Protagonist",
  "Phantasmal Treasure",
  "Phantom Crowd",
  "Phantom Orchestra",
  "Phantom Pain",
  "Phantom Prison",
  "Phase Bolt",
  "Phoenix Ward",
  "Pillar of Water",
  "Pillars of Sand",
  "Pinpoint",
  "Planar Palace",
  "Planar Seal",
  "Planar Tether",
  "Plant Form",
  "Pocket Library",
  "Polar Ray",
  "Pollen Pods",
  "Poltergeist's Fury",
  "Portrait of the Artist",
  "Positive Attunement",
  "Possession",
  "Power Word Blind",
  "Power Word Kill",
  "Power Word Stun",
  "Pressure Zone",
  "Prestidigitation",
  "Primal Chorus",
  "Primal Herd",
  "Primal Phenomenon",
  "Prismatic Armor",
  "Prismatic Shield",
  "Prismatic Sphere",
  "Prismatic Spray",
  "Prismatic Wall",
  "Procyal Philosophy",
  "Project Image",
  "Proliferating Eyes",
  "Prophet's Luck",
  "Propulsive Breeze",
  "Protect Companion",
  "Protection",
  "Protector Tree",
  "Prying Survey",
  "Puff of Poison",
  "Pummeling Rubble",
  "Punishing Winds",
  "Purifying Icicle",
  "Purple Worm Sting",
  "Putrefy Food and Drink",
  "Pyrefowl Rebuke",
  "Pyrotechnics",
  "Quandary",
  "Quench",
  "Quick Sort",
  "Quicken Time",
  "Radiant Beam",
  "Radiant Field",
  "Radiant Globe",
  "Radiant Heart of Devotion",
  "Rainbow Fumarole",
  "Rainbow's End",
  "Raise Dead",
  "Rally Point",
  "Rallying Banner",
  "Ranage's Circle",
  "Rapid Adaptation",
  "Ravening Maw",
  "Ravenous Darkness",
  "Ravenous Portal",
  "Ray of Corruption",
  "Ray of Frost",
  "Read Aura",
  "Read Omens",
  "Read the Air",
  "Reaper's Lantern",
  "Rebounding Barrier",
  "Recall Legacy",
  "Reed Whistle",
  "Reflected Beauty",
  "Reflective Scales",
  "Regenerate",
  "Remake",
  "Repelling Pulse",
  "Replicate",
  "Repulsion",
  "Resist Energy",
  "Resplendent Mansion",
  "Restoration",
  "Restore Ground",
  "Restyle",
  "Retrocognition",
  "Return Beacon",
  "Return To Essence",
  "Revealing Light",
  "Reverse Gravity",
  "Revival",
  "Rewinding Step",
  "Rewrite Memory",
  "Rigid Form",
  "Rime Slick",
  "Ring of Truth",
  "Rip the Spirit",
  "Ritual Obstruction",
  "Roaring Applause",
  "Root Reading",
  "Rope Trick",
  "Rose's Thorns",
  "Rouse Skeletons",
  "Rousing Splash",
  "Rubble Step",
  "Runic Body",
  "Runic Weapon",
  "Rust Cloud",
  "Rusting Grasp",
  "Sacred Beasts",
  "Sacred Form",
  "Sacred Nimbus",
  "Safe Passage",
  "Sage's Curse",
  "Sanctuary",
  "Sand Form",
  "Sanguine Mist",
  "Sawtooth Terrain",
  "Scatter Scree",
  "Schadenfreude",
  "Scintillating Safeguard",
  "Scorching Blast",
  "Scouring Pulse",
  "Scouring Sand",
  "Scouting Eye",
  "Scrying",
  "Scrying Ripples",
  "Sculpt Sound",
  "Sea Surge",
  "Sea of Thought",
  "Seal Fate",
  "Seashell of Stolen Sound",
  "Secret Chest",
  "Secret Page",
  "See the Unseen",
  "Seize Identity",
  "Seize Soul",
  "Sending",
  "Shadow Army",
  "Shadow Blast",
  "Shadow Projectile",
  "Shadow Raid",
  "Shadow Siphon",
  "Shadow Spy",
  "Shadow Zombie",
  "Shape Stone",
  "Shape Wood",
  "Share Life",
  "Share Lore",
  "Shared Invisibility",
  "Shatter",
  "Shattering Gem",
  "Shield",
  "Shielded Arm",
  "Shift Blame",
  "Shifting Sand",
  "Shillelagh",
  "Shock and Awe",
  "Shock to the System",
  "Shocking Grasp",
  "Shockwave",
  "Show the Way",
  "Shrink",
  "Shrink Item",
  "Siege Weapon's Blessing",
  "Sigil",
  "Sign of Conviction",
  "Signal Skyrocket",
  "Silence",
  "Skeleton Army",
  "Slashing Gust",
  "Sleep",
  "Sliding Blocks",
  "Slither",
  "Slough Skin",
  "Slow",
  "Snake Fangs",
  "Snowball",
  "Soft Landing",
  "Solid Fog",
  "Sonata Span",
  "Soothe",
  "Soothing Blossoms",
  "Soothing Spring",
  "Sound Body",
  "Sparkleskin",
  "Speak with Animals",
  "Speak with Plants",
  "Speak with Stones",
  "Spell Immunity",
  "Spell Riposte",
  "Spell Turning",
  "Spellwrack",
  "Spider Sting",
  "Spike Stones",
  "Spirit Blast",
  "Spirit Link",
  "Spirit Sense",
  "Spirit Song",
  "Spirit Ward",
  "Spiritual Anamnesis",
  "Spiritual Armament",
  "Spiritual Attunement",
  "Spiritual Epidemic",
  "Spiritual Guardian",
  "Spiritual Renewal",
  "Spiritual Torrent",
  "Spiritual Transport",
  "Spiritual Weapon",
  "Splinter Volley",
  "Spout",
  "Spy's Mark",
  "Stabilize",
  "Stagnate Time",
  "Status",
  "Steal Voice",
  "Steel Fortifications",
  "Sticky Fire",
  "Stifling Stillness",
  "Stinking Cloud",
  "Stone to Flesh",
  "Stonesense",
  "Storm of Vengeance",
  "Stormburst",
  "Strange Geometry",
  "Strength of Mind",
  "Stupefy",
  "Subconscious Suggestion",
  "Sudden Blight",
  "Sudden Bolt",
  "Sudden Recollection",
  "Sudden Transposition",
  "Suggestion",
  "Summon Anarch",
  "Summon Ancient Fleshforged",
  "Summon Animal",
  "Summon Archmage",
  "Summon Axiom",
  "Summon Celestial",
  "Summon Construct",
  "Summon Deific Herald",
  "Summon Draconic Legion",
  "Summon Dragon",
  "Summon Elemental",
  "Summon Elemental Herald",
  "Summon Entity",
  "Summon Fey",
  "Summon Fiend",
  "Summon Giant",
  "Summon Healing Servitor",
  "Summon Instrument",
  "Summon Irii",
  "Summon Kaiju",
  "Summon Lesser Servitor",
  "Summon Monitor",
  "Summon Oliphaunt of Jandelay",
  "Summon Plant or Fungus",
  "Summon Stampede",
  "Summon Undead",
  "Summon Warden of the Wild",
  "Summoner's Precaution",
  "Summoner's Visage",
  "Sunburst",
  "Sure Footing",
  "Sure Strike",
  "Suspended Retribution",
  "Swallow Light",
  "Swampcall",
  "Swarming Wasp Stings",
  "Synaptic Pulse",
  "Synchronize",
  "Synchronize Steps",
  "Synesthesia",
  "Tailwind",
  "Take Root",
  "Take Your Places",
  "Talking Corpse",
  "Tame",
  "Tangle Vine",
  "Tanglecurse",
  "Tangling Creepers",
  "Teeth to Terror",
  "Telekinetic Bombardment",
  "Telekinetic Hand",
  "Telekinetic Haul",
  "Telekinetic Maneuver",
  "Telekinetic Projectile",
  "Telepathic Bond",
  "Telepathic Demand",
  "Telepathy",
  "Teleport",
  "Tempest Cloak",
  "Tempest of Shades",
  "Temporal Twin",
  "Temporal Ward",
  "Temporary Glyph",
  "Temporary Tool",
  "Tether",
  "The Four Hunters",
  "The Parrot's Whisper",
  "The Queen's Rainbow",
  "Thermal Remedy",
  "Thicket of Knives",
  "Thief of Fortune",
  "Thoughtful Gift",
  "Threefold Aspect",
  "Threefold Limb",
  "Thundering Dominance",
  "Thunderstrike",
  "Timber",
  "Time Beacon",
  "Time Jump",
  "Time Pocket",
  "Time Sense",
  "Timely Tutor",
  "Tomorrow's Dawn",
  "Tortoise and the Hare",
  "Torturous Trauma",
  "Toxic Cloud",
  "Trade Items",
  "Transcribe Conflict",
  "Translate",
  "Translocate",
  "Transmute Rock And Mud",
  "Travel by Turtle",
  "Tree of Seasons",
  "Tremor Signs",
  "Tremorsense",
  "Trickster's Feathers",
  "Trim the Blight",
  "True Target",
  "Truesight",
  "Truespeech",
  "Umbral Extraction",
  "Umbral Graft",
  "Umbral Journey",
  "Umbral Mindtheft",
  "Unbroken Panoply",
  "Uncontrollable Dance",
  "Undermine Reality",
  "Undertaker",
  "Unexpected Transposition",
  "Unfathomable Song",
  "Unfettered Movement",
  "Unfettered Pack",
  "Unholy Army",
  "Unrelenting Observation",
  "Unseasonable Squall",
  "Unspeakable Shadow",
  "Upheaval",
  "Utter Destruction",
  "Vacuum",
  "Vampiric Exsanguination",
  "Vampiric Feast",
  "Vampiric Maiden",
  "Vanishing Tracks",
  "Vapor Form",
  "Variable Gravity",
  "Veil of Privacy",
  "Veil of Spirits",
  "Ventriloquism",
  "Verdant Sprout",
  "Verminous Lure",
  "Vibrant Pattern",
  "Vibrant Vibrato",
  "Vicious Jealousy",
  "Vision of Beauty",
  "Vision of Death",
  "Visions of Danger",
  "Vital Beacon",
  "Vitality Lash",
  "Vitrifying Blast",
  "Voice on the Breeze",
  "Void Warp",
  "Volcanic Eruption",
  "Vomit Swarm",
  "Voracious Gestalt",
  "Wails of the Damned",
  "Wall Of Mirrors",
  "Wall of Fire",
  "Wall of Flesh",
  "Wall of Force",
  "Wall of Ice",
  "Wall of Metal",
  "Wall of Radiance",
  "Wall of Shadow",
  "Wall of Shrubs",
  "Wall of Stone",
  "Wall of Thorns",
  "Wall of Virtue",
  "Wall of Water",
  "Wall of Wind",
  "Wanderer's Guide",
  "Warding Aggression",
  "Warp Mind",
  "Warp Step",
  "Warping Pull",
  "Warrior's Regret",
  "Wash Your Luck",
  "Water Breathing",
  "Water Walk",
  "Waterproof",
  "Wave of Despair",
  "Weaken Earth",
  "Weapon Storm",
  "Weapon of Judgment",
  "Weave Wood",
  "Web",
  "Web of Eyes",
  "Weird",
  "Whirling Scarves",
  "Whirlpool",
  "Whirlwind",
  "Whispers of the Void",
  "Winning Streak",
  "Wisdom of the Winds",
  "Wooden Double",
  "Wooden Fists",
  "Word of Revision",
  "Worm's Repast",
  "Wrathful Storm",
  "Wyvern Sting",
  "Ymeri's Mark",
  "Zealous Conviction",
  "Zephyr Slip",
  "Zero Gravity"
])
